alias pgcli="~/bin/pgcli/bin/pgcli"
alias weather="curl wttr.in/~Isle+of+Wight"
alias pubip="curl -4 icanhazip.com"
alias less="less -r"
[[ -f ~/.LESS_TERMCAP ]] && . ~/.LESS_TERMCAP
alias be="bundle exec"
alias checkport="sudo netstat -tnlp | grep"
alias dockerpurge="docker system prune --all --force --volumes"
alias dockerkill="docker stop \`docker ps -a -q\`"
alias vi="nvim"
alias tn="tmux new-window -n"
alias genpdf="pandoc -o migration.pdf -t ms"
CFLAGS="-Wall -Werror -Wextra"
alias cc="gcc ${CFLAGS}"
alias update_ruby_build="git -C "$(rbenv root)"/plugins/ruby-build pull"
alias irc="ssh kernighan -t tmux attach -t irc"

alias krc="kamal app exec -i --reuse 'bin/rails c'"
alias krd="kamal app exec -i --reuse 'bin/rails dbconsole'"
alias krb="kamal app exec -i --reuse 'bash'"

alias rlc="rails console"
alias rls="rails server"
alias rld="rails dbconsole -p"
alias rlr="rails routes"

alias dc="docker compose"
alias dce="docker compose exec"
alias dcb="docker compose exec web /bin/bash"
alias dcew="docker compose exec web"
alias dcbe="docker compose exec web bundle exec"
alias drlc="docker compose exec web bundle exec rails console"
alias drls="docker compose exec web bundle exec rails server"
alias drld="docker compose exec web bundle exec rails dbconsole -p"
alias drldm="dc exec web bundle exec rails db:migrate"
alias dcrldr="dc exec web bundle exec rails db:rollback"
alias drt='dc exec web bundle exec rspec'
